### ISSUE TITLE
Final comments from Emlyn

### ISSUE THREAD

**Issue by emlyn** [eudaq/StatusTelescope2015-Paper#12]
- pages 2, 3, 6, 8 & 16 (twice): "a EUDET" should be "a**n** EUDET"
- page 3, section 3: "The EUDET-type beam telescope**_s**_ are tabletop tracking detectors" (pluralise "telescope").
- page 3, section 3: "In the Cartesian, right-handed coordinate system chosen, the x-direction points horizontally and the z-direction along the beam direction.": I think this is ambiguous - there are two rotated coordinate systems that match the description (one with y pointing up, and one down), how about: "In the Cartesian, right-handed coordinate system chosen, the y-direction points vertically down and the z-direction along the beam direction." (I think this is the correct one, judging from figure 2).
- page 8, section 6: "c.f. section**s** 3 and 4" (pluralise "section")
- page 9, below eq. 3: "term σ<sub>t,b</sub>: **q**ualitatively," (lower case "q")
- page 13, last line: "which seems to overestimate the intrinsic resolution.": this is a bit confusing, I would interpret an overestimated resolution as being better (i.e. lower number), but this seems to be the opposite. However, replacing with "underestimate" could cause similar confusion, so I'm not sure how best to fix it. Maybe just leave it as is, you can always work out the direction from the numbers.
- page 14, section 6.2: "the actual DUT position z<sub>DUT</sub>, c.f. figure 2, can be made", maybe write as "the actual DUT position z<sub>DUT</sub> (cf. figure 2) can be made" (use parentheses instead of commas, and remove extra period from inside "cf" for consistency with other uses).

**Comment by TCThenna** [comment]
Thanks Emlyn for your comments. 

First five bullets: agreed and corrected
6) we came to the same conclusion that we leave it up to the reader to understand the direction of "over"-estimate as "being larger" rather than "being better". 
7) I cleaned the sentence a bit more (we repeated the value of 7.6e-4 which is already mentioned in section 3). Now it reads:

Using the measured intrinsic resolution and the material budget in the beam (telescope planes, air, DUT),  predictions of the track resolution at the actual DUT position $\zdut$ (cf.~figure~\ref{fig:datura_sketch}) are rendered possible.
