### ISSUE TITLE
Comments by AB

### ISSUE THREAD

**Issue by abulgher** [eudaq/StatusTelescope2015-Paper#5]
The paper is very well written, high quality and it will be for sure very much appreciated by the vast telescope user community. Well done, congratulations! 

I have a few general comments, you can decide to use them or not, the overall paper will not at all be affected!  

*) You mention many time "unbiased residual distribution". Maybe it is worth to explain what do you mean, also a reference to something else is enough. 
*) Section 5. I remember Philipp did a lot of work on the Millipede II integration. Without entering too much in the details, I would add which are the free parameters that the processor is minimizing. If I remember well, at the beginning we were neglecting shifts along the beam direction. Is it still the case? 
*) Section 6.3. I have seen these plots showing the resolution versus plane number and threshold several times as results of simulations. I'm happy to see that the reality is so close to our expectations. What do you think about adding a purity plot (or fake rate) beside Figure 6? You mention a single number at sigma = 6 in the section 3.1. If you don't have all the data to make the plot, it is probably already enough to repeat here this 2e-5. 
*) The resolution depends on the number of planes in the tracker. From what you say, you used either 6 or 5 planes depending on the configuration (user or gauge). Did you set in the analysis a constrain to accept only tracks having 6 or 5 hits respectively? If so, can you quantify how many tracks did you reject because of missing hits? Given the high efficiency of each single plane, I don't expect this number to be very high.
*) Section 6.4. Page 11 lines 21 - 22. You define here the gauge configuration to be compared with the user one. The difference is clear, but I would introduce the gauge configuration in the previous section where it is actually used. 
*) Page 13 Line 8. You mention dedicated alignment runs. I know you mean low multiplicity, but maybe it is worth to mention it in the paper as well. BTW, in section 3.1 you quote a maximum hit rate for the M26, but I couldn't find anywhere what is the maximum number of reconstructed tracks for event that the telescope can handle. Do you have an idea if with increasing multiplicity the pointing resolution is deteriorated by a "confusion" term? 

That's all for now...

**Comment by TCThenna** [comment]
Thanks a lot for your valuable comments.
- On page 7 line 22- 24, we describe what the residual distance is. I will add "unbiased" : " ... and the UNBIASED residual distance between ... and ... as well as ... are calculated.". I hope the reader understands that residual distances stemming from different tracks then form the residual distribution.
  I'll also add "unbiased" to p 8 line 30
- Well, we didnt open the box with weak modes in this paper, as we think this should be discussed in a dedicated EUTelescope paper. Do you think that this detail adds value for the reader to understand the results discussed in sec 6?
- if the noise is Gaussian, the 2e-5 that we quote for sigma = 6 will probably change appropriately for other thresholds. I'll have a look if purity is discussed in the Mimosa 26 paper we quote, and might add another quote in sec 6.3. We include the efficiency as this involves tacking. The noise is a pure sensor characteristic, so we only quoted it for sigma = 6 such that the reader knows the ball park number.
- The MEASUREMENTS are always done in a 5+1 configuration, so five M26 are the telescope, and one M26 is the DUT (Sec 6.3). In 6.4 we calculate, what resolution is achievable on the DUT when using 6 planes as telescope planes. Only for the comparison of the data with the GBL calculations (Figure 8 (A)), we calculated resolutions in the 5+1 configuration. 
  --> we didn't chose either 5 or 6 hits, as the measurement was always done with 5+1 planes.
  For tracking, we required a hit in every of the five planes to form a track. Up to now, we didn't study how the number of tracks change when requiring only 4 hits.
- Good point. I will add a sentence in 6.3. that the 5+1 configuration is the gauge configuration.
- Maybe we should make that more clear. The dedicated alignment runs do not need to be low multiplicity, as long it is not too high. The dedicated alignment runs should be WITHOUT a DUT, such that there is as less multiple scattering as possible for the alignment.
- The first bottle neck is the buffer size on the M26 limiting the number of "well separated" hits per read-out frame. With more and more particles traversing the sensors, the chip merges already fired pixels into larger entities as a result of the read-out scheme used. So it's not really easy to say... All in all, the answer to your question would need a dedicated run at high multiplicity machine like SLAC, increasing the multiplicity per "bunch" in sensible units. The high occupancy would lead to fired pixels being associated with clusters from another track, which will deteriorate the reconstructed position of the cluster with respect to the real one. Since this limit doesn't seem to be reached at neither DESY nor CERN, and not even at SLAC, your question is rather academic, I suppose :)

Thanks again for your comments.

**Comment by TCThenna** [comment]
"*) Section 6.3. I have seen these plots showing the resolution versus plane number and threshold several times as results of simulations. I'm happy to see that the reality is so close to our expectations. What do you think about adding a purity plot (or fake rate) beside Figure 6? You mention a single number at sigma = 6 in the section 3.1. If you don't have all the data to make the plot, it is probably already enough to repeat here this 2e-5. "
- I had a look again at the paper by Baudot et al [12]. They measured a noise (fake) rate of 6e-5 at a threshold of 6 and actually show the plot you asked for. I'll cite the paper again and quote the 6e-5 instead.
